### ISSUE TITLE
Add HTTPS to cart-api endpoint

### ISSUE THREAD

**Issue by maksumov** [maksumov/rss-shop-be#10]
# Task Definition

maksumov-cart-api is deployed, but for integration with App FE it must have HTTPS links. I expect to solve the problem by adding integration with HTTP proxy. Links to solution examples are published here: https://github.com/maksumov/rss-shop-be/issues/9#issuecomment-740240850

To implement solution I plan:
- [ ] to add cart-service service with API Gateway resolved to deployed maksumov-cart-api
- [x] or [manually add HTTPS proxy](https://github.com/maksumov/rss-shop-be/issues/10#issuecomment-740283696) to my HTTP endpoint by [this tutorial](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-create-api-as-simple-proxy-for-http.html).

**Comment by maksumov** [comment]
# Add new cart-service

## Add serverless service project based on typescript template

```bash
sls create -t aws-nodejs-typescript -p cart-service -n cart-service 
```

## Setup cart service

1. link service to serverless app dashboard adding `org` and `app`:
```ts
  org: "maksumov",
  app: "rss-store",
```
2. add `region` and `stage`:
```ts
provider: {
    region: "eu-west-1",
    stage: "dev",
```
3. add https proxy resources linked to my http endpoint:
    - [ ] _not yet implemented_

**Comment by maksumov** [comment]
# Manually created HTTP Proxy integration

maksumov-cart-api HTTP endpoint URL: http://maksumov-cart-api-dev.eu-west-1.elasticbeanstalk.com/
API Gateway HTTPS URL: https://u7dyaoudn4.execute-api.eu-west-1.amazonaws.com/dev/
Tutorial: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-create-api-as-simple-proxy-for-http.html
