### ISSUE TITLE
Task 9.2

### ISSUE THREAD

**Issue by maksumov** [maksumov/rss-shop-be#13]
# Task 9.2 Definition

- [x] Deploy bff-service with Elastic Beanstalk.
  - Platform should be node.js
  - Application name must follow the following convention {yours_github_account_login}-bff-api
  - Use the --cname option {yours_github_account_login}-bff-api-{environment_name}
  - Use the --single option
- [x] The bff-service should be deployed with Elastic Beanstalk. 
- [x] The bff-service call should be redirected to the appropriate service. 
- [x] The response from the bff-service should be the same as if the recipient service was called directly.

Source: https://github.com/rolling-scopes-school/nodejs-aws-tasks/blob/main/task9-bff/task.md

**Comment by maksumov** [comment]
# Some AWS Elastic Beanstalk Documentation about Nodejs Platform

- [Elastic Beanstalk supported platforms: Node.js](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported.nodejs)
- [Node.js platform options](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-specific.html#command-options-nodejs)
- [Configure environment properties for your Nodejs application](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html#command-options-general-elasticbeanstalkapplicationenvironment)
- [RS School Lecture: How to setup env variables for nodejs platform](https://youtu.be/_B5n11Tq2Pc?t=1430)
