### ISSUE TITLE
Task 8.1

### ISSUE THREAD

**Issue by maksumov** [maksumov/rss-shop-be#8]
# Task 8.1

Create Dockerfile that will build a docker image to run the service. You can use the example provided in the lecture as a starting point. Then, do following steps:

- [x] Add .dockerignore file to minimize build context. Files and folders generated by the application or npm should be excluded. Provide explanations to why the folder was ignored.
- [x] OPTIONAL: add more folders to .dockerignore with explanations
- [x] Minimize docker image size by applying techniques found in the lecture to be less than 500 MB.
- [x] OPTIONAL: Minimize docker image size to about 100 MB.
- [x] Optimize image build times. Dockerfile commands that run npm install should not depend on typescript files.
- [x] OPTIONAL: Optimize build times by utilizing multistage builds.
- [ ] OPTIONAL: Lint Dockerfile.

source: https://github.com/rolling-scopes-school/nodejs-aws-tasks/blob/main/task8-docker-elastic-beanstalk/task.md

**Comment by maksumov** [comment]
# Trying to optimize image size

## Useful commands

```bash
docker build -t cart-api .
docker images
docker history --human --format "{{.CreatedBy}}: {{.Size}}" cart-api
```

## Useful links

- https://www.youtube.com/watch?v=S6WfFEETW_s
- https://www.youtube.com/watch?v=LJX4FJrXW9U
- https://blog.logrocket.com/containerized-development-nestjs-docker/

**Comment by maksumov** [comment]
I managed to achieve an image size of less than 100 MB

![image](https://user-images.githubusercontent.com/9920913/101376538-c337f500-38c1-11eb-8ab5-29d18a69f082.png)

**Comment by maksumov** [comment]
`docker images` in LSW (ubuntu 20.04.1) after `docker build -t cart-api .`

![image](https://user-images.githubusercontent.com/9920913/101394811-17e76a00-38da-11eb-82a5-2a9ca6e40d6a.png)

`docker history --human --format "{{.CreatedBy}}: {{.Size}}" cart-api`:

![image](https://user-images.githubusercontent.com/9920913/101395025-672d9a80-38da-11eb-803d-961c926bb484.png)

**Comment by maksumov** [comment]
# Learn to run docker image

## Base Command to Run Container

```bash
docker container run [OPTIONS] cart-api [COMMAND] [ARG...]
```

## Options

| Option             	| Description                                        	|
|--------------------	|----------------------------------------------------	|
| -d, --detach       	| Run container in background and print container ID 	|
| -p, --publish list 	| Publish a container's port(s) to the host          	|
| --rm               	| Automatically remove the container when it exits   	|
| -i, --interactive  	| Keep STDIN open even if not attached               	|
| --init  	| Run an init inside the container that forwards signals and reaps processes              	|
| -t, --tty          	| Allocate a pseudo-TTY                              	|
| --name string      	| Assign a name to the container                     	|
| -v, --volume list  	| Bind mount a volume                                	|

### Run in background (detach mode)

Run container in background and print container ID: `docker container run -d cart-api`

-d, --detach                         Run container in background and print container ID

### Ports Mapping Option

`-p host_ip:host_port:container_port/protocol`

Example: `docker container run --name cart-api -d -p 8080:8080 cart-api`

## Other Useful Commands

### List Running Containers

```bash
docker container ls
```

### Stop Container

```bash
docker container stop <id or name>
```

## Sources:

1. https://devacademy.ru/article/izuchaem-komandu-docker-run-na-primerakh
2. `docker run --help`

## Command to Run Container with cart-api

Command to run our container in interactive mode:

```bash
docker container run --name cart-api --rm -it --init -p 8080:8080 cart-api
```

**Comment by maksumov** [comment]
# User Creation (in Docker Container)

Added user creation in Dockerfile according to https://habr.com/ru/post/448480/
