### ISSUE TITLE
Task 8.2

### ISSUE THREAD

**Issue by maksumov** [maksumov/rss-shop-be#9]
# Task 8.2

Deploy Cart API service with Elastic Beanstalk.

- [x] Use a Dockerfile from TASK 8.1 to deploy your Cart API using AWS EB CLI.
- [x] [Initiate an Elastic beanstalk application](https://github.com/maksumov/rss-shop-be/issues/9#issuecomment-740209997) using the `eb init` command. Application name must follow the following convention {yours_github_account_login}-cart-api.
- [x] [Create a new environment](https://github.com/maksumov/rss-shop-be/issues/9#issuecomment-740213101) using the `eb create` command. An environment name must be short but not less then four signs (e.g develop, test, prod, etc). Use the --cname option {yours_github_account_login}-cart-api-{environment_name} so that Elastic Beanstalk will use it to create a proper domain name. Use the --singe option to not use any Load Balancer for this environment.
- [x] Investigate AWS Elastic Beanstalk service in the AWS Console. Walk through EC2 resources that were created by Elastic Beanstalk
![image](https://user-images.githubusercontent.com/9920913/101425930-0e2b2a00-390d-11eb-8665-3227fb24e700.png)

- [x] [Update the app](https://github.com/maksumov/rs-cart-api/pull/1/commits/87d3eee846f2ffd6cf897758c3496dce0216d4a6#diff-ef0ff0ca9442bda67ad0810654d636991173ecd7c1abcd6da09288b8815759ff) and [deploy changes](http://maksumov-cart-api-dev.eu-west-1.elasticbeanstalk.com/ping) using the `eb deploy` command.
- [x] [Update FE app: pull the latest version of the app from repo](https://github.com/maksumov/nodejs-aws-fe/issues/8) and replace {cart} API placeholder in src/constants/apiPaths.ts using a Cart API url you get after successful deployment. Make sure your app starts to call Cart API when you add or remove items. Now after page refresh cart’s content might remain the same.

Source: https://github.com/rolling-scopes-school/nodejs-aws-tasks/blob/main/task8-docker-elastic-beanstalk/task.md

**Comment by maksumov** [comment]
# Elastic Beanstalk App Init

```bash
eb init -r eu-west-1 maksumov-cart-api
```

## Options

1. It appears you are using Docker. Is this correct? (Y/n): `y`
2. Select a platform branch: `Docker running on 64bit Amazon Linux` (option 3)
3. Do you wish to continue with CodeCommit? (Y/n): `n`
4. Do you want to set up SSH for your instances? `n`

![image](https://user-images.githubusercontent.com/9920913/101419863-fbf7be80-3901-11eb-8dde-79b05b128148.png)

**Comment by maksumov** [comment]
# Elastic Beanstalk Environment Create

```bash
eb create development --single --cname maksumov-cart-api-dev
```

## Used Options

- `--single` - do not use balancer
- `--cname` - use cname for **development** environment with name **maksumov-cart-api-dev**


![image](https://user-images.githubusercontent.com/9920913/101419825-e4203a80-3901-11eb-862c-a8ef1d38732c.png)

**Comment by maksumov** [comment]
# Add HTTPS to Elastic Beanstalk cart-api endpoint

The solution is to add HTTP proxy integration to the existing API of published cart-api.

Source:

1. https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-create-api-as-simple-proxy-for-http.html
2. https://github.com/serverless/serverless/pull/3534#issuecomment-463277409
